version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # package.json dosyasının olduğu dizin
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "react"
        versions: ["<18.0.0"]
