import Navbar from './components/navbar';
import MyProfilePic from './components/profilePic';
export const metadata = {
    title: 'Arif Özkan',
    description: 'Generated by Next.js',
    icons: './images/icon.ico',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <Navbar />
                {children}
            </body>
        </html>
    );
}
