'use client';
import { ThemeProvider } from 'next-themes';
import Navbar from './components/navbar';
import MyProfilePic from './components/profilePic';
import Head from 'next/head';
// export const metadata = {
//     title: 'Arif Özkan',
//     description: 'Generated by Next.js',
//     icons: './images/icon.ico',
// };
const titleVariable = 'asdasdsad';
export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body>
                <ThemeProvider attribute="class">
                    <Navbar />
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
