import Navbar from "./components/navbar";
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      
      <body className="dark:bg-slate-800">
        <Navbar/>{children}</body>
    </html>
  );
}
